export const clientData = [
  {
    name: "Dion Ang",
    status: "New Lead",
    email: "dionang@gmail.com",
    netWorth: 10000,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "John Toh",
    status: "Attempted to contact",
    email: "johntoh@gmail.com",
    netWorth: 57000,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Steven Lim",
    status: "Contacted",
    email: "stevenlim@gmail.com",
    netWorth: 5400,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Ryan Soh",
    status: "Qualified",
    email: "ryansoh@gmail.com",
    netWorth: 20550,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy fdsfds",
    status: "UnqualifiedvxcvxcvxcvxcvdsdadaUnqualifiedvxcvxcddxcvccs",
    email: "ryansoh@gmail.com",

    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy Hoh",
    status: "Unqualified",
    email: "lucyhoh@gmail.com",
    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy Hoh",
    status: "Unqualified",
    email: "lucyhoh@gmail.com",
    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy Hoh",
    status: "Unqualified",
    email: "lucyhoh@gmail.com",
    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy Hoh",
    status: "Unqualified",
    email: "lucyhoh@gmail.com",
    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy Hoh",
    status: "Unqualified",
    email: "lucyhoh@gmail.com",
    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy Hoh",
    status: "Unqualified",
    email: "lucyhoh@gmail.com",
    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
  {
    name: "Lucy Hoh",
    status: "Unqualified",
    email: "lucyhoh@gmail.com",
    netWorth: 11500,
    appointment: new Date("2023/11/03"),
  },
];
